version: '7.4-dev_r{build}'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "7.4.0.{build}"
  assembly_file_version: "7.4.0.{build}"
  assembly_informational_version: "{version}"

environment:
  matrix:
    - appveyor_build_worker_image: Visual Studio 2019
      configuration: Debug
      platform: Any CPU
    - appveyor_build_worker_image: Visual Studio 2019
      configuration: Release
      platform: Any CPU

before_build:
  - nuget restore

build:
  project: HedgeModManager.sln
  verbosity: minimal
  
artifacts:
 - path: 'HedgeModManager\bin\Debug'
   name: '$(appveyor_project_name) $(appveyor_build_version) [Debug]'
   type: zip
 - path: 'HedgeModManager\bin\Release'
   name: '$(appveyor_project_name) $(appveyor_build_version) [Release]'
   type: zip
   
