name: Windows Build

on:
  push:
    paths-ignore:
      # Ignore code files.
      - 'HedgeModManager/Resources/Codesv2/**'

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\HedgeModManager.sln

jobs:
  build:
    name: ${{matrix.configuration}}
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Add Git hash to resources
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: echo ${{github.sha}} > HedgeModManager/Resources/Version.txt

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{matrix.configuration}} ${{env.SOLUTION_FILE_PATH}}

    - uses: actions/upload-artifact@v2
      with:
        name: HedgeModManager-${{matrix.configuration}}
        path: ${{github.workspace}}\HedgeModManager\bin\${{matrix.configuration}}\net472
